
export const uiText: Record<string, Record<string, string>> = {
  en: {
    language: 'Language',
    shayari: '📜 Shayari',
    joke: '😂 Joke',
    motivational: '💪 Motivational',
    spiritual: '🧘 Spiritual',
    copiedToClipboard: 'Copied to clipboard!',
    shareInspiration: 'Share the inspiration.',
    imageGenerationFailed: 'Image Generation Failed',
    copied: 'Copied!',
    copyText: 'Copy Text',
    creating: 'Creating...',
    generateImage: 'Generate Image',
    showAnother: 'Show Another',
    yourImage: 'Your Morning Muse Image',
    downloadAndShare: 'Here is your generated image. Feel free to download and share it!',
    generatingMasterpiece: 'Generating your masterpiece...',
    downloadImage: 'Download Image',
    goodMorning: '🌞 Good Morning! 🌸',
    haveANiceDay: '☕️ Have a beautiful day ahead!',
  },
  hi: {
    language: 'भाषा',
    shayari: '📜 शायरी',
    joke: '😂 चुटकुला',
    motivational: '💪 प्रेरणादायक',
    spiritual: '🧘 आध्यात्मिक',
    copiedToClipboard: 'क्लिपबोर्ड पर कॉपी किया गया!',
    shareInspiration: 'प्रेरणा साझा करें।',
    imageGenerationFailed: 'छवि निर्माण में विफल',
    copied: 'कॉपी किया गया!',
    copyText: 'टेक्स्ट कॉपी करें',
    creating: 'बना रहा है...',
    generateImage: 'छवि बनाएं',
    showAnother: 'दूसरा दिखाओ',
    yourImage: 'आपकी मॉर्निंग म्यूज़ इमेज',
    downloadAndShare: 'यहां आपकी उत्पन्न छवि है। इसे डाउनलोड करने और साझा करने के लिए स्वतंत्र महसूस करें!',
    generatingMasterpiece: 'आपकी उत्कृष्ट कृति बना रहा है...',
    downloadImage: 'छवि डाउनलोड करें',
    goodMorning: '🌞 सुप्रभात! 🌸',
    haveANiceDay: '☕️ आपका दिन सुंदर हो!',
  },
  es: {
    language: 'Idioma',
    shayari: '📜 Shayari',
    joke: '😂 Broma',
    motivational: '💪 Motivacional',
    spiritual: '🧘 Espiritual',
    copiedToClipboard: '¡Copiado al portapapeles!',
    shareInspiration: 'Comparte la inspiración.',
    imageGenerationFailed: 'Falló la generación de la imagen',
    copied: '¡Copiado!',
    copyText: 'Copiar texto',
    creating: 'Creando...',
    generateImage: 'Generar imagen',
    showAnother: 'Mostrar otro',
    yourImage: 'Tu imagen de Morning Muse',
    downloadAndShare: 'Aquí está tu imagen generada. ¡Siéntete libre de descargarla y compartirla!',
    generatingMasterpiece: 'Generando tu obra maestra...',
    downloadImage: 'Descargar imagen',
    goodMorning: '🌞 ¡Buenos días! 🌸',
    haveANiceDay: '☕️ ¡Que tengas un hermoso día por delante!',
  },
};
