
export const uiText: Record<string, Record<string, string>> = {
  en: {
    language: 'Language',
    shayari: '📜 Shayari',
    joke: '😂 Joke',
    motivational: '💪 Motivational',
    spiritual: '🧘 Spiritual',
    festival: '🎉 Festival',
    copiedToClipboard: 'Copied to clipboard!',
    shareInspiration: 'Share the inspiration.',
    copied: 'Copied!',
    copyText: 'Copy Text',
    showAnother: 'Show Another',
    goodMorning: '🌞 Good Morning! 🌸',
    haveANiceDay: '☕️ Have a beautiful day ahead!',
    generatingMessage: 'Finding a festive greeting',
    generateImage: 'Generate Image',
    generatingImage: 'Generating...',
    downloadImage: 'Download Image',
    shareImage: 'Share Image',
    generatedImageTitle: 'Your Inspired Art',
    close: 'Close',
    imageShared: 'Image shared successfully!',
    shareFailed: 'Could not share image.',
  },
  hi: {
    language: 'भाषा',
    shayari: '📜 शायरी',
    joke: '😂 चुटकुला',
    motivational: '💪 प्रेरणादायक',
    spiritual: '🧘 आध्यात्मिक',
    festival: '🎉 त्यौहार',
    copiedToClipboard: 'क्लिपबोर्ड पर कॉपी किया गया!',
    shareInspiration: 'प्रेरणा साझा करें।',
    copied: 'कॉपी किया गया!',
    copyText: 'टेक्स्ट कॉपी करें',
    showAnother: 'दूसरा दिखाओ',
    goodMorning: '🌞 सुप्रभात! 🌸',
    haveANiceDay: '☕️ आपका दिन सुंदर हो!',
    generatingMessage: 'एक उत्सव की शुभकामना ढूंढ रहा हूँ',
    generateImage: 'छवि बनाएं',
    generatingImage: 'बना रहा है...',
    downloadImage: 'छवि डाउनलोड करें',
    shareImage: 'छवि साझा करें',
    generatedImageTitle: 'आपकी प्रेरित कला',
    close: 'बंद करें',
    imageShared: 'छवि सफलतापूर्वक साझा की गई!',
    shareFailed: 'छवि साझा नहीं हो सकी।',
  },
  es: {
    language: 'Idioma',
    shayari: '📜 Shayari',
    joke: '😂 Broma',
    motivational: '💪 Motivacional',
    spiritual: '🧘 Espiritual',
    festival: '🎉 Festival',
    copiedToClipboard: '¡Copiado al portapapeles!',
    shareInspiration: 'Comparte la inspiración.',
    copied: '¡Copiado!',
    copyText: 'Copiar texto',
    showAnother: 'Mostrar otro',
    goodMorning: '🌞 ¡Buenos días! 🌸',
    haveANiceDay: '☕️ ¡Que tengas un hermoso día por delante!',
    generatingMessage: 'Buscando un saludo festivo',
    generateImage: 'Generar imagen',
    generatingImage: 'Generando...',
    downloadImage: 'Descargar imagen',
    shareImage: 'Compartir imagen',
    generatedImageTitle: 'Tu arte inspirado',
    close: 'Cerrar',
    imageShared: '¡Imagen compartida con éxito!',
    shareFailed: 'No se pudo compartir la imagen.',
  },
};
